services:
  api:
    build: ./HighloadCourse
    container_name: highload_course_api
    environment:
      - ConnectionString=Server=highload_course_db;User Id=${DB_USER};Password=${DB_PASSWORD};Database=highload_course
      - AuthenticationKey=${AUTH_KEY}
    ports:
      - "5001:8080"
  db:
    image: postgres
    container_name: highload_course_db
    hostname: highload_course_db
    environment:
      - POSTGRES_DB=highload_course
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ~/postgresql:/var/lib/postgresql
      - ./../Scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./../Scripts/initialize_data.sh:/usr/scripts/initialize_data.sh
      - ./../Scripts/initialize_data.sql:/usr/scripts/initialize_data.sql
      - ./../Scripts/data.csv:/usr/scripts/data.csv
