services:
  api:
    build: ./HighloadCourse
    container_name: highload_course_api
    restart: always
    ports:
      - "5000:80"
  db:
    image: postgres
    container_name: highload_course_db
    restart: always
    hostname: highload_course_db
    ports:
      - "5001:5432"
    environment:
      - POSTGRES_DB=highload_course
      - POSTGRES_PASSWORD=pass@w0rd
    volumes:
      - ~/postgresql:/var/lib/postgresql
      - ./../Scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
