services:
  api:
    build: .
    container_name: highload_course_api
    restart: always
    ports:
      - "5000:80"
  db:
    image: postgres
    container_name: highload_course_db
    restart: always
    hostname: highload_course_db
    ports:
      - "5001:5432"
    environment:
      - POSTGRES_PASSWORD=pass@w0rd
    volumes:
      - ~/postgresql:/var/lib/postgresql
